### ISSUE TITLE
Logo licensing for Wikipedia?

### ISSUE THREAD

**Issue by Matthias84** [ExpressLRS/Docs#120]
Hi, I like to enrich the wikidata item with the logo. Unfortunatly there is no license and authorship on the logotype.svg.
Can you clearify if it's copyleft and if the project as a whole is a good author line?

**Comment by maybenikhil** [comment]
see: https://github.com/ExpressLRS/ExpressLRS-Hardware/tree/master/img/logo for attributions for the logo, I am not knowledgeable enough in copyright law to answer the rest of your question

**Comment by Matthias84** [comment]
Thanks for pointing me to the reference! I uploaded it and linked it to the WD entry:
https://www.wikidata.org/wiki/Q109808045
