### ISSUE TITLE
Describe USE_DYNAMIC_POWER user define

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#13]
From [#724](https://github.com/ExpressLRS/ExpressLRS/pull/724)

**Comment by jurgelenas** [comment]
I wrote this for the configurator app:

```
Dynamic power feature uses LQ-based power boost up to detect
quick drops in link quality and RSSI-based power adjustments
which are working slowly, suitable for a general long-range
flights.

This feature requires ENABLE_TELEMETRY.
```

**Comment by CapnBry** [comment]
The feature does not require ENABLE_TELEMETRY :-P I've got a doc started in the wiki for this and will get it in the website once I stop making updates.
https://github.com/ExpressLRS/ExpressLRS/wiki/Dynamic-Transmit-Power

**Comment by maybenikhil** [comment]
will wait to work on this until you finish the wiki page

**Comment by jurgelenas** [comment]
> The feature does not require ENABLE_TELEMETRY :-P I've got a doc started in the wiki for this and will get it in the website once I stop making updates.
> https://github.com/ExpressLRS/ExpressLRS/wiki/Dynamic-Transmit-Power

thanks, will update my description!

**Comment by jurgelenas** [comment]
Follow up?
