### ISSUE TITLE
Optional dark mode

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#22]
You can read about enabling dark mode on https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

It might require updating some of my CSS changes though

**Comment by deadbytefpv** [comment]
Interesting.. Let me play with this.. 
And I'll bet we want to give option between default and dark mode, correct?

**Comment by jurgelenas** [comment]
Yeah, dark mode switch in a header

**Comment by maybenikhil** [comment]
I've messed with it, and it made the color pallete we have look REALLY bad

**Comment by jurgelenas** [comment]
Awesome
