### ISSUE TITLE
Crystal Oscillator (XO) Frequency Error page

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#251]
It would be nice to have this page https://github.com/ExpressLRS/ExpressLRS/wiki/Crystal-Oscillator-(XO)-Frequency-Error on our docs website. I was trying to find it using our search, but no success!

Edit: forgot to tag @SunjunKim as owner of github wiki page.

**Comment by AghaSaad04** [comment]
Hi @jurgelenas, Thanks for pointing this out. 

Under which section do we need to add this page? Any pointers would be helpful. Thanks

**Comment by maybenikhil** [comment]
This could probably go into /hardware/ in the main section (or some subsection)

**Comment by maybenikhil** [comment]
Done #256
