### ISSUE TITLE
Document the need to have DEBUG_FREQ_CORRECTION set on both TX & RX at the same time

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#252]
User defines: https://www.expresslrs.org/3.0/software/user-defines/#debug-options

It looks like a person had an issue because that was not documented: https://github.com/ExpressLRS/ExpressLRS/issues/1835

**Comment by maybenikhil** [comment]
done. https://github.com/ExpressLRS/Docs/commit/6a033c1b906bc33f9bc3b680bfed37af48e8e65e
