### ISSUE TITLE
New Receivers for selection page.

### ISSUE THREAD

**Issue by FrenzyIncarnate** [ExpressLRS/Docs#258]
Hello. 
There are some new receivers that I've seen on the market that are not in [the receiver selection page ](https://www.expresslrs.org/3.0/hardware/receiver-selection/) 
I have gathered information for 2 of them and you can find it below. 
[elrs new receivers.xlsx](https://github.com/ExpressLRS/Docs/files/9794403/elrs.new.receivers.xlsx)
![image](https://user-images.githubusercontent.com/33299655/196034379-238f6598-76a4-4ca8-8d46-0399ab284545.png)

Thank you for your good work.

**Comment by maybenikhil** [comment]
Sorry for the slow reply - we need to do a more broad overhaul of that page in general which is on my list of things to do. Thanks for bringing it up, I appreciate the contribution

**Comment by BhaswatiRoy** [comment]
Hello, we can update the new receiver details in the receiver-selection.md file
I can work on this!

**Comment by maybenikhil** [comment]
In theory i'd like to change it to more of a feature guide than a list of every receiver because there are so many now, but I am not sure what my timeline for that is so if you'd like to add these in for the time being that would be alright as well

**Comment by BhaswatiRoy** [comment]
Hello @maybenikhil 
I have added the 2 new receivers in the receiver-selection.md file.
