### ISSUE TITLE
Vantac lite drivers CH340 does not work in Windows 11

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#280]
Drivers exec linked in https://www.expresslrs.org/3.0/quick-start/transmitters/vantac-lite/?h=vantac#flashing-via-usbuart V3.4 does not work properly on Windows 11. On wch-ic.com there is a newer one which supports Windows 11.

**Comment by maybenikhil** [comment]
done https://github.com/ExpressLRS/Docs/commit/9f6bb630b5efdecdbc49a851dcbec4fab732649a

although the old one did work for flashing the vantac I have
