### ISSUE TITLE
RC Link Presets

### ISSUE THREAD

**Issue by hyp0dermik-code** [ExpressLRS/Docs#379]
Here or BF wiki?

**Comment by deadbytefpv** [comment]
Would be great to have under "Before First Flight" page. Either before the Blackbox section or after the Modes section.

Thanks!

**Comment by VitroidFPV** [comment]
It would be a good contribution to the BF wiki too though :)

**Comment by maybenikhil** [comment]
done in #405 - although definitely should be followed up for betaflight
