### ISSUE TITLE
Add another row in LED status for RGB

### ISSUE THREAD

**Issue by Belrmar** [ExpressLRS/Docs#381]
On https://www.expresslrs.org/quick-start/led-status/ , a new line on the rgb LED stating that no light can indicate it's on bootloader mode

**Comment by Senk02** [comment]
I'll handle this one.

**Comment by Senk02** [comment]
This should be fixed/made more clear with pull #402 .

**Comment by MUSTARDTIGERFPV** [comment]
#402 fixed this, thanks @Senk02~!
