### ISSUE TITLE
Update ESP Backpack page

### ISSUE THREAD

**Issue by microraptor** [ExpressLRS/Docs#40]
The first sentence of the page always confuses me, because the Happymodel modules already have the backpack integrated, but it doesn't mention that anywhere. Or which modules have them and which don't:

---

Addon for **R9M modules**, **HappyModel ELRS915TX**, and **HappyModel ES24TX** to allow:

* Logging to Browser and via Websocket
* Flashing ESP Backpack (self)
* Flashing R9M TX
* Possibly more.. wireless trainer mode? Please contribute :1st_place_medal:

This is a convenience feature for development purposes and "power users" - soldering can be tricky - please be careful. :police_officer:

---

Instead I would suggest to have the page start something like this (my example also has to be changed, because I don't know enough; see the edit below):

---

Addon for ExpressLRS TX modules to allow:

* Logging to Browser and via Websocket
* Flashing ESP Backpack (self)
* Flashing the TX module
* Bluetooth Joystick (ESP32 only)
* Possibly more... wireless trainer mode, VRX connection or telemetry broadcasting? Please contribute :1st_place_medal:

TX modules with an ESP32 already integrated:

* Happymodel ES24TX
* Happymodel ES900TX
* BetaFPV Nano 2.4GHz
* BetaFPV Nano 900Mhz

TX modules confirmed to be working with a DIY ESP backpack (see instructions below):

* Frsky R9M

TX modules not compatible with the backpack:

?

This is a convenience feature for development purposes and "power users" - soldering can be tricky - please be careful. :police_officer:

---

Edit:
I did some more reading and am more confused now. The Happymodel and BetaFPV TX modules seem to be using the internal ESP32 for WiFi updates and Bluetooth. So I am not sure, if on the Happymodel the extra ESP backpack is even used for now. Is there even an advantage of having an extra ESP backpack? It would be great if the page could clarify this. Also there is a section in the instructions for a "Happymodel ELRS915TX", but I can't find any information on this module. Is it the same as a "Happymodel ES900TX"?

**Comment by maybenikhil** [comment]
THE ELRS915TX is not the ES900TX, and I believe there may have been a few ES24TXes that did not have an ESP backpack but i can check with the developers

**Comment by maybenikhil** [comment]
Done in https://github.com/ExpressLRS/Docs/commit/452771ec25090fe31c0813168f8123662317b31c, where I remove mention of ES24TX, but ELRS915TX does have compatibility.
