### ISSUE TITLE
[2.0] Update Model Configuration and Matching Behavior Documentation

### ISSUE THREAD

**Issue by maybenikhil** [ExpressLRS/Docs#62]
This requires updating software/model-config-matching.md and quick-start/lua-howto.md to be in line with the new behavior of model Matching

**Comment by CapnBry** [comment]
@pkendall64 have you started this task? If not I can make a whole page about it for the docs. There's not a ton to say about it, but I think too much to cram into the modelmatch section of the Lua page
https://www.expresslrs.org/2.0/quick-start/lua-howto/#model-match

**Comment by pkendall64** [comment]
No, I haven't, sorry. I did the initial cut which @maybenikhil made a lot nicer, but I think it just needs the Set RX Model removed and then a once-over the whole thing.

**Comment by CapnBry** [comment]
> No, I haven't, sorry. I did the initial cut which @maybenikhil made a lot nicer, but I think it just needs the Set RX Model removed and then a once-over the whole thing.

Roger that. I just wanted to ask to make sure that we weren't going to be duplicating work. I'll make a draft PR tomorrow.
