### ISSUE TITLE
MY_STARTUP_MELODY supports RTTTL format now

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#9]
`MY_STARTUP_MELODY` user define now support melodies in RTTTL format: https://github.com/ExpressLRS/ExpressLRS/pull/641. I think it might be good to mention that somewhere in the docs.

**Comment by jurgelenas** [comment]
I even got an issue about this in the configurator repository: https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/14

**Comment by jurgelenas** [comment]
This is my update to the configurator regarding this: https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/4f144bf2f427d65e430204ac3df6ff80c733c33b

**Comment by maybenikhil** [comment]
will update
