### ISSUE TITLE
Add description for USE_TX_BACKPACK user define

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/Docs#92]
See: https://github.com/ExpressLRS/ExpressLRS/blob/master/src/user_defines.txt#L67

**Comment by CapnBry** [comment]
The `USE_ESP8266_BACKPACK` should also be removed from user-defines and added to obsolete-defines. Note that the link to obsolete-defines is broken and should link to `obsolete-defines` but links to `Obsolete-user_defines` instead so that should be fixed as well.

**Comment by maybenikhil** [comment]
is this broken on both master & dev or just one?

**Comment by maybenikhil** [comment]
just dev oops

**Comment by CapnBry** [comment]
That wasn't for you, I was just making a note for myself when I addressed this issue. Go back to class!

**Comment by maybenikhil** [comment]
i was doing this real quick haha, i'll stop now

**Comment by CapnBry** [comment]
Haha you can do it if you want, but it's my define so it's on my to do list to document it. We do have a bunch of doc PRs piled up though kissy face emoji

**Comment by CapnBry** [comment]
Only took me three weeks but I DID IT!
